export const kuwaitAreas = {
  "Al Ahmadi": [
    "Ahmadi",
    "Fahaheel",
    "Mangaf",
    "Mahboula",
    "Sabah Al Ahmad",
    "Abu Halifa",
    "Egaila",
    "Hadiya",
    "Riqqa",
    "Sabahiya",
    "Daher",
    "Wafra",
  ],

  Farwaniya: [
    "Farwaniya",
    "Khaitan",
    "Omariya",
    "Andalous",
    "Jleeb Al-Shuyoukh",
    "Ardiya",
    "Rabiya",
    "Rahab",
    "Abdullah Al Mubarak",
  ],

  Hawalli: [
    "Hawalli",
    "Salmiya",
    "Jabriya",
    "Bayan",
    "Mishref",
    "Salwa",
    "Rumaithiya",
    "Shaab",
    "Surra",
  ],

  Capital: [
    "Dasman",
    "Qibla",
    "Mirqab",
    "Kaifan",
    "Shamiya",
    "Adailiya",
    "Abdullah Al Salem",
    "Khaldiya",
    "Qadsiya",
    "Shuwaikh",
  ],

  "Mubarak Al-Kabeer": [
    "Adan",
    "Qurain",
    "Qusour",
    "Sabah Al Salem",
    "Abu Al Hasaniya",
    "Messila",
    "Fnaitees",
  ],

  "Al Jahra": [
    "Jahra",
    "Saad Al Abdullah",
    "Naseem",
    "Taima",
    "Oyoun",
    "Qasr",
    "Waha",
    "Sulaibiya",
  ],
};
