export const scheduleData = [
  {
    id: 1,
    serviceType: "campus-off",
    serviceLabel: "Campus-Off",
    route: "Shuwaikh → Al-Shadadiya",
    category: "College of Social Sciences",
    campusPath: "Shuwaikh Campus → Al-Shadadiya",
    departureLocation: "College of Social Sciences - Shuwaikh Area",
    destination: "Al-Shadadiya Main Campus",
    status: "Available",
    type: "Mixed",
    departure: "08:00",
    arrival: "08:30",
    bus: "BUS-003 (Masar)",
    seats: 0,
    total: 40,
  },
  {
    id: 2,
    serviceType: "campus-off",
    serviceLabel: "Campus-Off",
    route: "Jabriya → Al-Shadadiya",
    category: "College of Medicine",
    campusPath: "Jabriya Campus → Al-Shadadiya",
    departureLocation: "College of Medicine - Jabriya Area",
    destination: "Al-Shadadiya Main Campus",
    status: "Available",
    type: "Mixed",
    departure: "09:00",
    arrival: "09:25",
    bus: "BUS-004 (Masar)",
    seats: 0,
    total: 40,
  },
  {
    id: 3,
    serviceType: "campus-off",
    serviceLabel: "Campus-Off",
    route: "Adailiya → Al-Shadadiya",
    category: "College of Architecture",
    campusPath: "Adailiya Campus → Al-Shadadiya",
    departureLocation: "College of Architecture - Adailiya Area",
    destination: "Al-Shadadiya Main Campus",
    status: "In Transit",
    type: "Mixed",
    departure: "07:30",
    arrival: "08:00",
    bus: "BUS-005 (Masar)",
    seats: 0,
    total: 50,
  },

  {
    id: 4,
    serviceType: "college",
    serviceLabel: "Masar",
    route: "North Campus → South Campus",
    category: "Internal Shuttle",
    campusPath: "North Campus → South Campus",
    departureLocation: "North Campus - Engineering & Petroleum",
    destination: "South Campus - Science",
    status: "Available",
    type: "Mixed",
    departure: "08:50",
    arrival: "09:10",
    bus: "BUS-001 (Internal)",
    seats: 0,
    total: 40,
  },
  {
    id: 5,
    serviceType: "college",
    serviceLabel: "Masar",
    route: "South Campus → North Campus",
    category: "Internal Shuttle",
    campusPath: "South Campus → North Campus",
    departureLocation: "South Campus - Arts",
    destination: "North Campus - Sharia & Islamic Studies",
    status: "Available",
    type: "Mixed",
    departure: "10:00",
    arrival: "10:15",
    bus: "BUS-002 (Internal)",
    seats: 0,
    total: 40,
  },

  {
    id: 6,
    serviceType: "beeyout",
    serviceLabel: "Beeyout",
    route: "Hawalli City → Al-Shadadiya",
    category: "Home Pickup",
    campusPath: "Hawalli → Al-Shadadiya",
    departureLocation: "Hawalli City (Home)",
    destination: "Al-Shadadiya Main Campus",
    status: "Available",
    type: "Female Only",
    departure: "06:30",
    arrival: "07:10",
    bus: "BUS-010 (Beeyout)",
    seats: 0,
    total: 25,
  },
  {
    id: 7,
    serviceType: "beeyout",
    serviceLabel: "Beeyout",
    route: "Salmiya City → Al-Shadadiya",
    category: "Home Pickup",
    campusPath: "Salmiya → Al-Shadadiya",
    departureLocation: "Salmiya City (Home)",
    destination: "Al-Shadadiya Main Campus",
    status: "Available",
    type: "Female Only",
    departure: "06:40",
    arrival: "07:15",
    bus: "BUS-011 (Beeyout)",
    seats: 0,
    total: 25,
  },
  {
    id: 8,
    serviceType: "beeyout",
    serviceLabel: "Beeyout",
    route: "Farwaniya City → Al-Shadadiya",
    category: "Home Pickup",
    campusPath: "Farwaniya → Al-Shadadiya",
    departureLocation: "Farwaniya City (Home)",
    destination: "Al-Shadadiya Main Campus",
    status: "Available",
    type: "Female Only",
    departure: "07:00",
    arrival: "07:45",
    bus: "BUS-012 (Beeyout)",
    seats: 0,
    total: 30,
  },
];

export const beeyoutData = [
  {
    id: 1,
    route: "Hawalli City → Beeyout",
    status: "Available",
    type: "Female",
    priority: "Female Only",
    departure: "06:30",
    arrival: "07:10",
    bus: "BUS-010 (Beeyout)",
    seats: 4,
    total: 25,
  },
  {
    id: 2,
    route: "Salmiya City → Beeyout",
    status: "Full",
    type: "Female",
    priority: "Female Only",
    departure: "06:40",
    arrival: "07:15",
    bus: "BUS-011 (Beeyout)",
    seats: 0,
    total: 25,
  },
  {
    id: 3,
    route: "Farwaniya City → Beeyout",
    status: "Available",
    type: "Female",
    priority: "Female Only",
    departure: "07:00",
    arrival: "07:45",
    bus: "BUS-012 (Beeyout)",
    seats: 6,
    total: 30,
  },
];

export const studentReports = [
  {
    id: 1,
    route: "Shuwaikh → Al-Shadadiya",
    text: "Bus was 10 minutes late.",
    status: "Resolved",
  },
  {
    id: 2,
    route: "Jabriya → Al-Shadadiya",
    text: "AC was not working properly.",
    status: "Pending",
  },
];

export const notifications = [
  {
    id: 1,
    text: "Bus BUS-003 will depart in 10 minutes from Main Gate.",
    route: "Shuwaikh → Al-Shadadiya",
    bus: "BUS-003",
    time: "01/03/2026, 7:50:00 AM",
  },
  {
    id: 2,
    text: "Your Beeyout subscription is active.",
    route: "Hawalli City → Al-Shadadiya",
    bus: "BUS-010",
    time: "01/03/2026, 6:20:00 AM",
  },
  {
    id: 3,
    text: "Driver marked BUS-005 as in transit.",
    route: "Adailiya → Al-Shadadiya",
    bus: "BUS-005",
    time: "01/03/2026, 7:30:00 AM",
  },
];
